package integrity

import (
	"errors"
	"io/fs"
	"os"

	"github.com/acoseac/1-bit-bridge/internal/analyze"
)

// The waveform half of the relocation story.
//
// `track_analysis.waveform_path` is absolute, exactly like
// `track_variants.sidecar_path`, and it has the same failure: copy the
// database to a host where `dataDir` sits elsewhere — or move the
// directory — and every row reads ENOENT while every curve sits,
// byte-identical, at its source-mirrored place under the CURRENT one.
//
// It is the WORSE half, and that is why it needed its own change rather
// than riding along with the variants one (#937 named it; #938 tracked
// it). A variant that reads missing gets regenerated by the
// auto-optimize sweeper, expensively but automatically. A waveform does
// not: the analysis skip gate keys on the SOURCE's mtime and size, both
// unchanged by a host move, so the candidate walk never offers the
// track again and `/v1/waveform` answers 410 forever. `bridge doctor`'s
// sidecar-paths check reports the state and tells the operator to
// re-run analysis — a full re-decode of the library to recover files
// that are already on disk.
//
// Deliberately NOT a reaper. Nothing here deletes: LocateWaveform
// classifies, and its one caller adopts. There is no waveform twin of
// VariantWatcher's reverse sweep, so a missing curve simply stays
// missing, which is the pre-existing behaviour.

// WaveformSnapshot is the subset of a `track_analysis` row the
// relocation probe needs. The waveform twin of VariantSnapshot.
type WaveformSnapshot struct {
	// SourcePath is the library-relative path the row is keyed on, and
	// the input the canonical layout is derived from.
	SourcePath string
	// WaveformPath is the absolute path the row RECORDS.
	WaveformPath string
	// SizeBytes is the row's recorded sidecar size, compared against a
	// file found at the canonical location so a partial copy is never
	// adopted.
	SizeBytes int64
}

// CanonicalWaveformPath is where row's curve belongs under waveformDir
// — `analyze.AnalyzeSpec.SidecarPath()`, the one layout the analysis
// pool writes and `analyze --gc`'s known set already derives. Empty
// when the row carries no source identity or no directory is known, so
// a caller can range over rows and skip the empties.
//
// Derived from the owning package rather than re-spelled here, for the
// reason CanonicalSidecarPath delegates to transcode.VariantSidecarPath:
// two copies of a layout is two things that can drift, and the one that
// drifts is the one that decides whether a file is adopted or orphaned.
func CanonicalWaveformPath(waveformDir string, row WaveformSnapshot) string {
	if waveformDir == "" || row.SourcePath == "" {
		return ""
	}
	return analyze.AnalyzeSpec{OutputDir: waveformDir, SourceLibraryRel: row.SourcePath}.SidecarPath()
}

// LocateWaveform stats the recorded path and, on ENOENT, the canonical
// one. Pure classification — it writes nothing, so the caller acts on
// the verdict in its own way. The verdicts and their meanings are
// LocateSidecar's, down to os.Stat rather than Lstat (a symlink to a
// missing target is missing from the serving path's point of view) and
// the exact size compare (the writer stat'd it after the atomic rename,
// and a waveform is never modified in place, so a partial copy can
// never be adopted).
func LocateWaveform(waveformDir string, row WaveformSnapshot) SidecarLocation {
	_, err := os.Stat(row.WaveformPath)
	if err == nil {
		return SidecarLocation{Verdict: SidecarPresent}
	}
	if !errors.Is(err, fs.ErrNotExist) {
		return SidecarLocation{Verdict: SidecarUnknown, Err: err}
	}
	canonical := CanonicalWaveformPath(waveformDir, row)
	if canonical == "" || canonical == row.WaveformPath {
		return SidecarLocation{Verdict: SidecarMissing}
	}
	info, err := os.Stat(canonical)
	switch {
	case err == nil && info.Mode().IsRegular() && info.Size() == row.SizeBytes:
		return SidecarLocation{Verdict: SidecarRelocated, Canonical: canonical}
	case err == nil:
		return SidecarLocation{Verdict: SidecarMismatched, Canonical: canonical}
	case errors.Is(err, fs.ErrNotExist):
		return SidecarLocation{Verdict: SidecarMissing, Canonical: canonical}
	default:
		return SidecarLocation{Verdict: SidecarUnknown, Canonical: canonical, Err: err}
	}
}
