package integrity

import (
	"github.com/acoseac/1-bit-bridge/internal/analyze"
)

// The waveform half of the relocation story.
//
// `track_analysis.waveform_path` is absolute, exactly like
// `track_variants.sidecar_path`, and it has the same failure: copy the
// database to a host where `dataDir` sits elsewhere — or move the
// directory — and every row reads ENOENT while every curve sits,
// byte-identical, at its source-mirrored place under the CURRENT one.
//
// It is the WORSE half, and that is why it needed its own change rather
// than riding along with the variants one (#937 named it; #938 still
// tracks the schema-relative follow-up). A variant that reads missing
// gets regenerated by the auto-optimize sweeper, expensively but
// automatically. A waveform does not: the analysis skip gate keys on the
// SOURCE's mtime and size, both unchanged by a host move, so the
// candidate walk never offers the track again. BEFORE adoption that left
// `/v1/waveform` answering 410 forever and `bridge doctor` prescribing a
// full re-decode to recover curves that were already on disk.
//
// LocateWaveform is what closed it: analysisStoreAdapter.LookupAnalysis
// adopts on the first lookup, serving from the canonical path and
// rewriting the row — no `indexed_at` bump, because a path correction
// changes nothing a client can see. There is still no proactive waveform
// sweep, so a curve heals when its track is next asked for and not
// before; that is the whole remaining gap, and it costs nothing while it
// lasts.
//
// Deliberately NOT a reaper. Nothing here deletes: LocateWaveform
// classifies, and its one caller adopts. There is no waveform twin of
// VariantWatcher's reverse sweep, so a missing curve simply stays
// missing, which is the pre-existing behaviour.

// WaveformSnapshot is the subset of a `track_analysis` row the
// relocation probe needs. The waveform twin of VariantSnapshot.
type WaveformSnapshot struct {
	// SourcePath is the library-relative path the row is keyed on, and
	// the input the canonical layout is derived from.
	SourcePath string
	// WaveformPath is the absolute path the row RECORDS.
	WaveformPath string
	// SizeBytes is the row's recorded sidecar size, compared against a
	// file found at the canonical location so a partial copy is never
	// adopted.
	SizeBytes int64
}

// CanonicalWaveformPath is where row's curve belongs under waveformDir
// — `analyze.AnalyzeSpec.SidecarPath()`, the one layout the analysis
// pool writes and `analyze --gc`'s known set already derives. Empty
// when the row carries no source identity or no directory is known, so
// a caller can range over rows and skip the empties.
//
// Derived from the owning package rather than re-spelled here, for the
// reason CanonicalSidecarPath delegates to transcode.VariantSidecarPath:
// two copies of a layout is two things that can drift, and the one that
// drifts is the one that decides whether a file is adopted or orphaned.
func CanonicalWaveformPath(waveformDir string, row WaveformSnapshot) string {
	if waveformDir == "" || row.SourcePath == "" {
		return ""
	}
	return analyze.AnalyzeSpec{OutputDir: waveformDir, SourceLibraryRel: row.SourcePath}.SidecarPath()
}

// LocateWaveform stats the recorded path and, on ENOENT, the canonical
// one. Pure classification — it writes nothing, so the caller acts on
// the verdict in its own way.
//
// It DELEGATES to locateRecordedFile rather than restating the ladder:
// this and LocateSidecar make the same decision about two different
// tables, and there is no reading on which they should answer
// differently. A second copy would be a second place to fix the day a
// verdict moves, and the copy that drifts is the one deciding whether a
// file is adopted or stranded. All this function owns is WHERE a
// waveform belongs; the classifier owns what the answer means.
func LocateWaveform(waveformDir string, row WaveformSnapshot) SidecarLocation {
	return locateRecordedFile(row.WaveformPath, CanonicalWaveformPath(waveformDir, row), row.SizeBytes)
}
